### ISSUE TITLE
Tensorflow lite C libs compilation issue

### ISSUE THREAD

**Issue by scryptosan** [mattn/go-tflite#21]
Hello! Hope you doing great!

I'm new in C-golang world and looks like i'm doing something wrong.
I tried libraries installation documentation from tensorflow-lite website, but it doesn't work for me.

I tried to compile TF lite C libraries with various Bazel versions and tf versions (1.15.0 and 1.15.2) on Mac and Linux docker, but every time i have errors like:

$ bazel build --config opt --config monolithic //tensorflow/lite/c:libtensorflowlite_c.so
ERROR: no such target '//tensorflow/lite/c:libtensorflowlite_c.so': target 'libtensorflowlite_c.so' not declared in package 'tensorflow/lite/c' defined by ~/sources/tmp/tf/tensorflow-1.15.0/tensorflow/lite/c/BUILD

$ bazel build --config opt --config monolithic tensorflow:libtensorflow_c.so
ERROR: no such target '//tensorflow:libtensorflow_c.sols': target 'libtensorflow_c.sols' not declared in package 'tensorflow' (did you mean 'libtensorflow_cc.so'?) defined by ~/sources/tmp/tf/tensorflow-1.15.0/tensorflow/BUILD

Only this library compile OK
$ bazel build --config opt --config monolithic //tensorflow/lite:libtensorflowlite.so

installation pipeline looks like:
1) install Bazel 0.24.1
2) wget  https://github.com/tensorflow/tensorflow/archive/v1.15.0.tar.gz and unpack sources
3) ./configure in tf sources root
4) run Bazel build stuff from README

Looks like i'm doing something wrong, but I don't understand what.
Could you please help me with installation?

Thanks!

**Comment by mattn** [comment]
Easy way to build libtensorflowlite.so is using tensorflow/lite/tools/make/Makefile.

**Comment by scryptosan** [comment]
I found issue:
for r1.15.2
in README 

$ bazel build --config opt --config monolithic //tensorflow/lite/c:libtensorflowlite_c.so

$ bazel build --config opt --config monolithic //tensorflow/lite/**experemental**/c:libtensorflowlite_c.so
