### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by rushabhnagda11** [mattn/go-tflite#23]
Hey, I'm curious to know if this has go-tflite has been tried on devices like the rasberry pi?

I'm currently rebuilding the libtensorflow_c.so file for ARM devices to use along on my rasberry pi, if this has been done before, would love to hear how that turned out to be.

If not, once I make any headway, I can share what I did to get things right. Let me know :)

**Comment by mattn** [comment]
I'm using go-tflite on Raspberry Pi 3B+.

**Comment by rushabhnagda11** [comment]
Hey sorry if this is too much to ask, but possible to share the libtensorflow_c.so file? or the tflite.so files?

Any instructions on how to get started would be very much appreciated

**Comment by rushabhnagda11** [comment]
@mattn Curious to know whether you were running raspbian OS or Ubuntu on the Rasberry Pi 3B+?

**Comment by mattn** [comment]
Recently I switched to Ubuntu from Raspbian OS. And both works.

**Comment by rushabhnagda11** [comment]
Hey finally managed to get this working on raspbian. I'll share the exact files and steps that worked for me or maybe create a docker out of the repo.
