### ISSUE TITLE
Guide for Raspberry Pi? (cannot find -ltensorflow-lite)

### ISSUE THREAD

**Issue by KyungWonPark** [mattn/go-tflite#29]
Hello

Could you write tutorial for setting this up in raspberry pi?

I'm trying to build it but I'm stuck at 

```
/usr/bin/ld: cannot find -ltensorflow-lite
```

Thank you

**Comment by KyungWonPark** [comment]
I'm building tensorflow lite library according to this official guide

https://www.tensorflow.org/lite/guide/build_rpi

Would this fix "cannot find -ltensorflow-lite" problem?

**Comment by KyungWonPark** [comment]
I made it!
Closing this issue
I'll write a guide about it

**Comment by danhartma** [comment]
Hey! Can you please share the guide to solve this problem?
Thanks in advance!
