### ISSUE TITLE
Can you add a license?

### ISSUE THREAD

**Issue by snowzach** [mattn/go-tflite#3]
This is great work. I actually got this to work with r14 and have been playing around with it. 

I would like to open source my code but would feel better if I either got your permission to release my code (which includes much of yours) or for you to add a license. (preferably BSD) Feel free to copy this and put your name in it's place: https://github.com/snowzach/gorestapi/blob/master/LICENSE.md

I have added support for the Coral edgetpu hardware accelerator. 

Thanks!

**Comment by mattn** [comment]
Thanks.

**Comment by mattn** [comment]
>I have added support for the Coral edgetpu hardware accelerator.

Cool!

**Comment by snowzach** [comment]
Thank you! I added you as a collaborator. Once it's ready I'll make it public. https://github.com/snowzach/tfaasgo

**Comment by mattn** [comment]
Thank your suggestion. However, I do not want to refer other source code and copy it into my source code. If you will make pull-request to this repository, I can merge it.

**Comment by snowzach** [comment]
Sure, if I ever figure it out right I will. I am still having some issues with it. I was mostly just adding you in case you wanted to check it out. I don't think the edgetpu library was ever designed to be wrapped by a C library and then Go. It prints the initialization string twice and then complains it can't find the tpu context. It then proceeds to work fine though. It took me hours and hour and hours to get this far.
