### ISSUE TITLE
Cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Jonarod** [mattn/go-tflite#4]
Hey, I wanted to try your promising library so I went through all the steps to produce my `libtensorflowlite_c.so` :smiley:. 

I then copy/pasted your `label_image` example and ran it using `go run main.go` producing this error:

```
/tmp/go-build075675325/b001/exe/main: error while loading shared libraries: libtensorflowlite_c.so: cannot open shared object file: No such file or directory
exit status 127
```

I understand my `libtensorflowlite_c.so` may not be placed in the correct location. However, in `https://github.com/mattn/go-tflite/blob/master/tflite.go` I see...

```
#cgo LDFLAGS: -L${SRCDIR}/../../tensorflow/tensorflow/tensorflow/lite/experimental/c -ltensorflowlite_c
```
...which seems to refer to the actual path my file sits in. So I don't really get why it cannot find it. Did I miss something ? Is there another step necessary to run `go-tflite` a part from placing the c library in tensorflow repo ?

P.S: just to make it clear, here is an extract of my tree:

```
$GOPATH/src/
    |_ github.com/
        |_ mattn/
        |       |_ go-tflite/
        |       |_ go-pointer/
        |_ Jonarod/
        |       |_ tests-labels-tflite/
        |           |_ main.go
        |_ tensorflow/
                |_ tensorflow/
                    |_ tensorflow/
                        |_ lite/
                            |_ experimental / c / libtensorflowlite_c.so
```

**Comment by lambdabaa** [comment]
@mattn Related,  could you upload a `libtensorflowlite_c.dll` (maybe through the releases GitHub functionality) so I can sanity check whether my issues are with the DLL or something else?

**Comment by mattn** [comment]
@lambdabaa I built this dll with the mingw64 compiler. (Note that I can not be responsible for any problems that occur)
[libtensorflowlite_c.zip](https://github.com/mattn/go-tflite/files/3438166/libtensorflowlite_c.zip)

**Comment by mattn** [comment]
@Jonarod You should copy libtensorflowlite_c.so into your /usr/local/lib or somewhere that is entried in  your $PATH. Or you can specify LD_LIBRARY_PATH to the locaiton.

**Comment by lambdabaa** [comment]
> @lambdabaa I built this dll with the mingw64 compiler. (Note that I can not be responsible for any problems that occur)

Thank you! It was an issue with the way I was building the DLL. I think it would be super helpful if you could provide some guidance in the `README` in regards to your mingw64 environment and the steps you took to run the make-based build successfully. Nice work!

**Comment by Jonarod** [comment]
It works ! THANK YOU THANK YOU !!!

**Comment by lambdabaa** [comment]
@mattn Have you been able to build a DLL after the tflite C API changes and would you be able to share it? Thanks!

**Comment by zmajew** [comment]
I have followed the instructions from here and still have:
 /tmp/go-build1465283250/b001/exe/main: error while loading shared libraries: libtensorflowlite_c.so: cannot open shared object file: No such file or directory
exit status 127
I put the libtensorflowlite_c.so into the /usr/local/lib and export LD_LIBRARY_PATH=/usr/local/lib and in /etc/environment but does not help. 
I am tryint go run esrgan example.
What I am missing?
