### ISSUE TITLE
status = interpreter.Invoke() takes one second or more

### ISSUE THREAD

**Issue by zmajew** [mattn/go-tflite#45]
Hi, 
I have created a Docker builder image for arm64v8 so I can compile binary from my code using your framework.

All is ok on the local ubuntu amd64 machine, but when I start the binary (compiled for arm64) on raspberry arm64v8, Invoke is slow, about a second or more.

`status = interpreter.Invoke() //takes more than 1 second`

Do you know about this issue and where the problem might be?

Raspberry is using arm64v8 architecture
For building the builder image I was using an ec2 arm machine (m6g.8xlarge)

**Comment by zmajew** [comment]
On the ec2 machine, all is ok too. Both Raspberry and ec2 are arch64 architecture

**Comment by mattn** [comment]
do you use delegate?

**Comment by zmajew** [comment]
I have to rebuild the builder docker image to try it since it returns to me:
`fatal error: edgetpu_c.h: No such file or directory
But, still, the delay is huge, more than 1000ms on interpreter.Invoke(). 
I have noticed that when I am using the arm64 binary (but in docker) locally on amd64 ubuntu, the delay is about 10 seconds. When I am using the same docker image on Raspberry delay is about 5 seconds So, my suspicion was on cross-compile.
On the ec2 machine the delay is 70 milliseconds.

**Comment by mattn** [comment]
I tried to build & run go-tflite on aarch64 (arm64).

![image](https://user-images.githubusercontent.com/10111/164721969-49af4333-9260-4211-bab8-5a8502926d5f.png)

**Comment by mattn** [comment]
Without XNNPACK delegate
![image](https://user-images.githubusercontent.com/10111/164722338-897439cb-e231-4287-92cc-9fa64dd3ea24.png)

**Comment by zmajew** [comment]
The same speed I have on the AWS ec2 cloud machine, even so my model has 90MB, but on raspberry it is ten-time slower.

**Comment by zmajew** [comment]
This is not an issue. The results are fine. The time differences are just because of the machine's performance. Thank you for your time and please excuse me for opening the issue. You can delete it
