### ISSUE TITLE
/usr/lib//libtensorflowlite_c.so: undefined reference to `tflite::Subgraph::AllocateTensors()'

### ISSUE THREAD

**Issue by CarterLi999** [mattn/go-tflite#53]
go build _example/sin/main.go
# command-line-arguments
/usr/local/go/pkg/tool/linux_riscv64/link: running gcc failed: exit status 1
/usr/bin/ld: /usr/lib/libtensorflowlite_c.so: undefined reference to `tflite::Subgraph::AllocateTensors()'
/usr/bin/ld: /usr/lib/libtensorflowlite_c.so: undefined reference to `tflite::impl::SignatureRunner::ResizeInputTensorStrict(char const*, std::vector<int, std::allocator<int> > const&)'
/usr/bin/ld: /usr/lib/libtensorflowlite_c.so: undefined reference to `tflite::impl::FlatBufferModel::VerifyAndBuildFromFile(char const*, tflite::TfLiteVerifier*, tflite::ErrorReporter*)'
/usr/bin/ld: /usr/lib/libtensorflowlite_c.so: undefined reference to `tflite::Subgraph::Cancel()'
/usr/bin/ld: /usr/lib/libtensorflowlite_c.so: undefined reference to `tflite::impl::Interpreter::SetBufferHandle(TfLiteTensor*, int, TfLiteDelegate*)'
/usr/bin/ld: /usr/lib/libtensorflowlite_c.so: undefined reference to `tflite::impl::Interpreter::ResetVariableTensors()'
/usr/bin/ld: /usr/lib/libtensorflowlite_c.so: undefined reference to `tflite::impl::Interpreter::SetNumThreads(int)'
/usr/bin/ld: /usr/lib/libtensorflowlite_c.so: undefined reference to `tflite::impl::SignatureRunner::output_tensor(char const*) const'

lib location:
/usr/lib/libtensorflow-lite.a  /usr/lib/libtensorflowlite_c.so

tflite::Subgraph::AllocateTensors()  should be defined in libtensorflow-lite.a ?  I have set CGO_LDFLAGS="-L/usr/lib -ltensorflow-lite".

Can you help me with this problem.

Best regards.

**Comment by mattn** [comment]
Your libtensorflow-lite.a does not link to flatbuffers. So it may be fixed with linking to libflatbuffers. Another thing, you libtensorflow-lite.a is not same that is liked from libtensorflowlite_c.so

**Comment by CarterLi999** [comment]
> Your libtensorflow-lite.a does not link to flatbuffers. So it may be fixed with linking to libflatbuffers. Another thing, you libtensorflow-lite.a is not same that is liked from libtensorflowlite_c.so

Thanks for your reply

Your libtensorflow-lite.a does not link to flatbuffers. So it may be fixed with linking to libflatbuffers. 
-> I wil try to link libflatbuffers

Another thing, you libtensorflow-lite.a is not same that is liked from libtensorflowlite_c.so
->I didn't get it. This means i use different interface between libtensorflow-lite.a and  libtensorflowlite_c.so?

**Comment by mattn** [comment]
>This means i use different interface between libtensorflow-lite.a and libtensorflowlite_c.so?

Yes, one of them are older which does have missing symbols.

**Comment by CarterLi999** [comment]
> > This means i use different interface between libtensorflow-lite.a and libtensorflowlite_c.so?
> 
> Yes, one of them are older which does have missing symbols.

I  will check on this. Thanks a lot  :）
